use_frameworks!

target 'CircleWithArrowHead_Example' do
  pod 'CircleWithArrowHead', :path => '../'

  target 'CircleWithArrowHead_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
